### ISSUE TITLE
CI - script for testing CKE5 dependencies

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-dev-tests#13]
Very simple and working solution is adding this package as a dev-dependency to each CKE5 dependency and use gulp to run the tests.

```bash
# An example for ckeditor5-engine
$ gulp test --files=engine
```

Unfortunately, we have a lot of packages and size of `node_modules` directory will be too huge. We would like to avoid to keep `ckeditor5-dev-tests` in each project.

We could create a `bin` script which will run the tests. It can be similar to test script [what I've created yesterday for testing CI](https://github.com/pomek/ckeditor5-ci/blob/master/bin/test.js).

When the script will be ready, on Travis we will be able to run scenario:

```yml
install:
  - npm install
  - npm install @ckeditor/ckeditor5-dev-tests
script:
  - node_modules/@ckeditor/ckeditor5-dev-tests/bin/test-script.js
```

It allows testing dependency using `ckeditor5-dev-tests` from CI.
