### ISSUE TITLE
Code Climate does not show the code coverage

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-dev-tests#16]
The problem has been reported a few days ago - https://github.com/ckeditor/ckeditor5/issues/354#issuecomment-258818841

I figured out what we need to do. `lcov.info` file contains the code coverage report with paths to files after compilation. These paths are incorrect - they don't exist in a repository so Code Climate doesn't understand the report.

We need to somehow fix the paths before sending the report to Code Climate.

**Comment by Reinmar** [comment]
Please keep `.travis.yml` short. So don't add there a big `sed` call.

**Comment by pomek** [comment]
Most probably this ticket can be solved by adding short `sed` command into `.travis.yml` before sending the report to Code Climate:

```diff
+   - sed -i.backup 's/\.build\/ckeditor5\/[^\/]*/src/g' .build/coverage/lcov.info
```

The whole `.travis.yml`:

```yml
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "6"
cache:
  - node_modules
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - npm install @ckeditor/ckeditor5-dev-tests
  - npm install codeclimate-test-reporter
script:
  - node_modules/.bin/ckeditor5-dev-tests --coverage
after_success:
  - sed -i.backup 's/\.build\/ckeditor5\/[^\/]*/src/g' .build/coverage/lcov.info
  - node_modules/.bin/codeclimate-test-reporter < .build/coverage/lcov.info
```
